<?xml version="1.0"?>
<config>
    <modules>
        <[Package]_[Module]>
            <version>[version]</version>
        </[Package]_[Module]>
    </modules>
    <global>
        <models>
            <[module]>
                <class>[Package]_[Module]_Model</class>
                <resourceModel>[module]_resource</resourceModel>
            </[module]>
            <[module]_customer>
                <class>[Package]_[Module]_Model_Customer</class>
                <!-- <resourceModel>[module]_customer_mysql4</resourceModel> -->
                <resourceModel>[module]_customer_resource</resourceModel>
            </[module]_customer>
            <[module]_resource>
                <class>[Package]_[Module]_Model_Resource</class>
                <deprecatedNode>[module]_mysql4</deprecatedNode>
                <entities>
                    <[module]>
                        <table>[module]</table>
                    </[module]>
                    <relation>
                        <table>[module]_relation</table>
                    </relation>
                    <summary>
                        <table>[module]_summary</table>
                    </summary>
                    <properties>
                        <table>[module]_properties</table>
                    </properties>
                </entities>
            </[module]_resource>
            <[module]_customer_resource>
                <class>[Package]_[Module]_Model_Customer_Resource</class>
            </[module]_customer_resource>
        </models>
        <resources>
            <[module]_setup>
                <setup>
                    <module>[Package]_[Module]</module>
                </setup>
            </[module]_setup>
        </resources>
        <blocks>
            <[module]>
                <class>[Package]_[Module]_Block</class>
            </[module]>
        </blocks>
        <index>
            <indexer>
                <[module]_summary>
                    <model>[module]/indexer_summary</model>
                </[module]_summary>
            </indexer>
        </index>
    </global>
    <frontend>
        <routers>
            <[module]>
                <use>standard</use>
                <args>
                    <module>[Package]_[Module]</module>
                    <frontName>[module]</frontName>
                </args>
            </[module]>
        </routers>
        <translate>
            <modules>
                <[Package]_[Module]>
                    <files>
                        <default>[Package]_[Module].csv</default>
                    </files>
                </[Package]_[Module]>
            </modules>
        </translate>
        <layout>
            <updates>
                <[module] module="[Package]_[Module]">
                    <file>[module].xml</file>
                </[module]>
            </updates>
        </layout>
        <secure_url>
            <[module]_customer>/[module]/customer/</[module]_customer>
        </secure_url>
    </frontend>
    <adminhtml>
        <events>
            <catalog_controller_product_save_visibility_changed>
                <observers>
                    <[module]>
                        <type>model</type>
                        <class>[module]/[module]</class>
                        <method>productEventAggregate</method>
                    </[module]>
                </observers>
            </catalog_controller_product_save_visibility_changed>
            <catalog_controller_product_delete>
                <observers>
                    <[module]>
                        <type>model</type>
                        <class>[module]/[module]</class>
                        <method>productEventAggregate</method>
                    </[module]>
                </observers>
            </catalog_controller_product_delete>
            <catalog_product_delete_before>
                <observers>
                    <[module]>
                        <type>model</type>
                        <class>[module]/[module]</class>
                        <method>productDeleteEventAction</method>
                    </[module]>
                </observers>
            </catalog_product_delete_before>
        </events>
        <translate>
            <modules>
                <[Package]_[Module]>
                    <files>
                        <default>[Package]_[Module].csv</default>
                    </files>
                </[Package]_[Module]>
            </modules>
        </translate>
        <layout>
            <updates>
                <[module]>
                    <file>[module].xml</file>
                </[module]>
            </updates>
        </layout>
    </adminhtml>
</config>